name: Creepair Test Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
    - name: Build with Maven
      run: mvn clean package
    - uses: actions/upload-artifact@v2
      with:
          name: Creepair (#${{ github.run_number }})
          path: |
            target/Creepair/
            target/*.jar

        
